pipeline {
    agent any

    stages {
        stage('Build Docker image') {
            steps {
                echo 'Creating Docker image...'
            }
            
        }
        stage('Deploy to Kubernetes') {
            steps {
                echo 'Deploing to kubernetes....'
            }
            
        }
        stage('Start python server') {
            steps {
                sh '''
                cd website
                nohup python3 -m http.server 8000 &
                '''
            }
        }
    }
}
