pipeline {
    agent any

    stages {
        stage('Build Docker image') {
            steps {
                echo 'Creating Docker image...'
            }
            
        }
        
        stage('Deploy to Kubernetes') {
            steps {
                echo 'Deploing to kubernetes....'
            }
        }

        stage('Debug Workspace') {
            steps {
                sh 'pwd'
                sh 'ls -la'
            }
        }        

        stage('Start python server') {
            steps {
                sh '''
                cd website
                nohup python3 -m http.server 8000 &
                '''
            }
        }
    }
    
}

